name: build_contents

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y z80asm make

      - name: Run Makefile
        working-directory: ./roms
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: roms.zip
          path: |
            roms/generated/contents.bin
            roms/generated/0-contents.afp
            roms/generated/1-BASICNL1.1.afp
            roms/generated/2-Forth.afp
            roms/generated/3-UCSD-Pascal.afp
            roms/generated/4-assembler-5.9.afp
            roms/generated/5-JWSBasic.afp
            roms/generated/6-familiegeheugen-4.afp
            roms/generated/7-Maintenance-2.afp
