name: build_contents

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y z80asm make

      - name: Run Makefile
        working-directory: ./roms
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: roms.zip
          path: |
            roms/generated/contents.bin
            roms/generated/contents.afp
            roms/generated/BASICNL1.1.afp
            roms/generated/Forth.afp
            roms/generated/UCSD-Pascal.afp
            roms/generated/assembler-5.9.afp
            roms/generated/JWSBasic.afp
            roms/generated/familiegeheugen-4.afp
            roms/generated/Maintenance-2.afp
